name: Build Electron App

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        type: string
        default: "main"

jobs:
  check_branch:
    runs-on: ubuntu-latest
    outputs:
      branch_exists: ${{ steps.check.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if branch exists
        id: check
        run: |
          if git rev-parse --verify ${{ github.event.inputs.branch }} >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check_branch
    if: needs.check_branch.outputs.branch_exists == 'true'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Make Electron App
        run: npm run make
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.os }}
          path: |
            out/make/**/*.dmg
            out/make/**/*.exe
            out/make/**/*.zip
          retention-days: 5

  error_if_branch_not_found:
    needs: check_branch
    if: needs.check_branch.outputs.branch_exists != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Error on non-existent branch
        run: |
          echo "Branch '${{ github.event.inputs.branch }}' does not exist"
          exit 1
